// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: Get.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MasterGetServiceClient is the client API for MasterGetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterGetServiceClient interface {
	// CheckAndGet Called by client.
	// Check whether the path and file name entered by the user in the Add operation are legal.
	CheckAndGet(ctx context.Context, in *CheckAndGetArgs, opts ...grpc.CallOption) (*CheckAndGetReply, error)
	// GetDataNodes4Get Called by client.
	// Allocate some DataNode to store a Chunk and select the primary DataNode
	GetDataNodes4Get(ctx context.Context, in *GetDataNodes4GetArgs, opts ...grpc.CallOption) (*GetDataNodes4GetReply, error)
	// ReleaseLease4Add Called by client.
	// Release the lease of a chunk.
	ReleaseLease4Get(ctx context.Context, in *ReleaseLease4GetArgs, opts ...grpc.CallOption) (*ReleaseLease4GetReply, error)
}

type masterGetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterGetServiceClient(cc grpc.ClientConnInterface) MasterGetServiceClient {
	return &masterGetServiceClient{cc}
}

func (c *masterGetServiceClient) CheckAndGet(ctx context.Context, in *CheckAndGetArgs, opts ...grpc.CallOption) (*CheckAndGetReply, error) {
	out := new(CheckAndGetReply)
	err := c.cc.Invoke(ctx, "/pb.MasterGetService/CheckAndGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterGetServiceClient) GetDataNodes4Get(ctx context.Context, in *GetDataNodes4GetArgs, opts ...grpc.CallOption) (*GetDataNodes4GetReply, error) {
	out := new(GetDataNodes4GetReply)
	err := c.cc.Invoke(ctx, "/pb.MasterGetService/GetDataNodes4Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterGetServiceClient) ReleaseLease4Get(ctx context.Context, in *ReleaseLease4GetArgs, opts ...grpc.CallOption) (*ReleaseLease4GetReply, error) {
	out := new(ReleaseLease4GetReply)
	err := c.cc.Invoke(ctx, "/pb.MasterGetService/ReleaseLease4Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterGetServiceServer is the server API for MasterGetService service.
// All implementations must embed UnimplementedMasterGetServiceServer
// for forward compatibility
type MasterGetServiceServer interface {
	// CheckAndGet Called by client.
	// Check whether the path and file name entered by the user in the Add operation are legal.
	CheckAndGet(context.Context, *CheckAndGetArgs) (*CheckAndGetReply, error)
	// GetDataNodes4Get Called by client.
	// Allocate some DataNode to store a Chunk and select the primary DataNode
	GetDataNodes4Get(context.Context, *GetDataNodes4GetArgs) (*GetDataNodes4GetReply, error)
	// ReleaseLease4Add Called by client.
	// Release the lease of a chunk.
	ReleaseLease4Get(context.Context, *ReleaseLease4GetArgs) (*ReleaseLease4GetReply, error)
	mustEmbedUnimplementedMasterGetServiceServer()
}

// UnimplementedMasterGetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMasterGetServiceServer struct {
}

func (UnimplementedMasterGetServiceServer) CheckAndGet(context.Context, *CheckAndGetArgs) (*CheckAndGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAndGet not implemented")
}
func (UnimplementedMasterGetServiceServer) GetDataNodes4Get(context.Context, *GetDataNodes4GetArgs) (*GetDataNodes4GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataNodes4Get not implemented")
}
func (UnimplementedMasterGetServiceServer) ReleaseLease4Get(context.Context, *ReleaseLease4GetArgs) (*ReleaseLease4GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLease4Get not implemented")
}
func (UnimplementedMasterGetServiceServer) mustEmbedUnimplementedMasterGetServiceServer() {}

// UnsafeMasterGetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterGetServiceServer will
// result in compilation errors.
type UnsafeMasterGetServiceServer interface {
	mustEmbedUnimplementedMasterGetServiceServer()
}

func RegisterMasterGetServiceServer(s grpc.ServiceRegistrar, srv MasterGetServiceServer) {
	s.RegisterService(&MasterGetService_ServiceDesc, srv)
}

func _MasterGetService_CheckAndGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAndGetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterGetServiceServer).CheckAndGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MasterGetService/CheckAndGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterGetServiceServer).CheckAndGet(ctx, req.(*CheckAndGetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterGetService_GetDataNodes4Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataNodes4GetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterGetServiceServer).GetDataNodes4Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MasterGetService/GetDataNodes4Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterGetServiceServer).GetDataNodes4Get(ctx, req.(*GetDataNodes4GetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterGetService_ReleaseLease4Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLease4GetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterGetServiceServer).ReleaseLease4Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MasterGetService/ReleaseLease4Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterGetServiceServer).ReleaseLease4Get(ctx, req.(*ReleaseLease4GetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterGetService_ServiceDesc is the grpc.ServiceDesc for MasterGetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterGetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MasterGetService",
	HandlerType: (*MasterGetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAndGet",
			Handler:    _MasterGetService_CheckAndGet_Handler,
		},
		{
			MethodName: "GetDataNodes4Get",
			Handler:    _MasterGetService_GetDataNodes4Get_Handler,
		},
		{
			MethodName: "ReleaseLease4Get",
			Handler:    _MasterGetService_ReleaseLease4Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Get.proto",
}

// SetupStreamClient is the client API for SetupStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetupStreamClient interface {
	// SetupStream2DataNode Called by client.
	// Set up the stream between client and chunkserver, then chunkserver returns data
	SetupStream2DataNode(ctx context.Context, in *SetupStream2DataNodeArgs, opts ...grpc.CallOption) (SetupStream_SetupStream2DataNodeClient, error)
}

type setupStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewSetupStreamClient(cc grpc.ClientConnInterface) SetupStreamClient {
	return &setupStreamClient{cc}
}

func (c *setupStreamClient) SetupStream2DataNode(ctx context.Context, in *SetupStream2DataNodeArgs, opts ...grpc.CallOption) (SetupStream_SetupStream2DataNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &SetupStream_ServiceDesc.Streams[0], "/pb.SetupStream/SetupStream2DataNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &setupStreamSetupStream2DataNodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SetupStream_SetupStream2DataNodeClient interface {
	Recv() (*Piece, error)
	grpc.ClientStream
}

type setupStreamSetupStream2DataNodeClient struct {
	grpc.ClientStream
}

func (x *setupStreamSetupStream2DataNodeClient) Recv() (*Piece, error) {
	m := new(Piece)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SetupStreamServer is the server API for SetupStream service.
// All implementations must embed UnimplementedSetupStreamServer
// for forward compatibility
type SetupStreamServer interface {
	// SetupStream2DataNode Called by client.
	// Set up the stream between client and chunkserver, then chunkserver returns data
	SetupStream2DataNode(*SetupStream2DataNodeArgs, SetupStream_SetupStream2DataNodeServer) error
	mustEmbedUnimplementedSetupStreamServer()
}

// UnimplementedSetupStreamServer must be embedded to have forward compatible implementations.
type UnimplementedSetupStreamServer struct {
}

func (UnimplementedSetupStreamServer) SetupStream2DataNode(*SetupStream2DataNodeArgs, SetupStream_SetupStream2DataNodeServer) error {
	return status.Errorf(codes.Unimplemented, "method SetupStream2DataNode not implemented")
}
func (UnimplementedSetupStreamServer) mustEmbedUnimplementedSetupStreamServer() {}

// UnsafeSetupStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetupStreamServer will
// result in compilation errors.
type UnsafeSetupStreamServer interface {
	mustEmbedUnimplementedSetupStreamServer()
}

func RegisterSetupStreamServer(s grpc.ServiceRegistrar, srv SetupStreamServer) {
	s.RegisterService(&SetupStream_ServiceDesc, srv)
}

func _SetupStream_SetupStream2DataNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetupStream2DataNodeArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SetupStreamServer).SetupStream2DataNode(m, &setupStreamSetupStream2DataNodeServer{stream})
}

type SetupStream_SetupStream2DataNodeServer interface {
	Send(*Piece) error
	grpc.ServerStream
}

type setupStreamSetupStream2DataNodeServer struct {
	grpc.ServerStream
}

func (x *setupStreamSetupStream2DataNodeServer) Send(m *Piece) error {
	return x.ServerStream.SendMsg(m)
}

// SetupStream_ServiceDesc is the grpc.ServiceDesc for SetupStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetupStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SetupStream",
	HandlerType: (*SetupStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetupStream2DataNode",
			Handler:       _SetupStream_SetupStream2DataNode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Get.proto",
}
