// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: Move.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckAndMoveArgs
// sourcePath: path of the directory or file need to be moved
// targetPath: path where directory or file will be moved to
type CheckAndMoveArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourcePath string `protobuf:"bytes,1,opt,name=sourcePath,proto3" json:"sourcePath,omitempty"`
	TargetPath string `protobuf:"bytes,2,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
}

func (x *CheckAndMoveArgs) Reset() {
	*x = CheckAndMoveArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Move_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAndMoveArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndMoveArgs) ProtoMessage() {}

func (x *CheckAndMoveArgs) ProtoReflect() protoreflect.Message {
	mi := &file_Move_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndMoveArgs.ProtoReflect.Descriptor instead.
func (*CheckAndMoveArgs) Descriptor() ([]byte, []int) {
	return file_Move_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAndMoveArgs) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *CheckAndMoveArgs) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type CheckAndMoveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckAndMoveReply) Reset() {
	*x = CheckAndMoveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Move_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAndMoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndMoveReply) ProtoMessage() {}

func (x *CheckAndMoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_Move_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndMoveReply.ProtoReflect.Descriptor instead.
func (*CheckAndMoveReply) Descriptor() ([]byte, []int) {
	return file_Move_proto_rawDescGZIP(), []int{1}
}

var File_Move_proto protoreflect.FileDescriptor

var file_Move_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x52, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x65,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6e, 0x64,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x50, 0x0a, 0x11, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b,
	0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x65,
	0x41, 0x72, 0x67, 0x73, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41,
	0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x05, 0x5a, 0x03, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Move_proto_rawDescOnce sync.Once
	file_Move_proto_rawDescData = file_Move_proto_rawDesc
)

func file_Move_proto_rawDescGZIP() []byte {
	file_Move_proto_rawDescOnce.Do(func() {
		file_Move_proto_rawDescData = protoimpl.X.CompressGZIP(file_Move_proto_rawDescData)
	})
	return file_Move_proto_rawDescData
}

var file_Move_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Move_proto_goTypes = []interface{}{
	(*CheckAndMoveArgs)(nil),  // 0: pb.CheckAndMoveArgs
	(*CheckAndMoveReply)(nil), // 1: pb.CheckAndMoveReply
}
var file_Move_proto_depIdxs = []int32{
	0, // 0: pb.MasterMoveService.CheckAndMove:input_type -> pb.CheckAndMoveArgs
	1, // 1: pb.MasterMoveService.CheckAndMove:output_type -> pb.CheckAndMoveReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Move_proto_init() }
func file_Move_proto_init() {
	if File_Move_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Move_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAndMoveArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Move_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAndMoveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Move_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Move_proto_goTypes,
		DependencyIndexes: file_Move_proto_depIdxs,
		MessageInfos:      file_Move_proto_msgTypes,
	}.Build()
	File_Move_proto = out.File
	file_Move_proto_rawDesc = nil
	file_Move_proto_goTypes = nil
	file_Move_proto_depIdxs = nil
}
